#!/bin/bash

# This script skips the built library archive files and runs a Hello World
# test directly. This is good for a quick smoke test.

# This should be run from the root project directory.

gcc \
    -I/usr/include/qt4/ \
    -c source/dqt/qstring_cpp.cpp \
    -o /tmp/qstring_cpp.o &&
rdmd \
    -I../dstruct/source \
    -I../dsmoke/source \
    -Isource \
    -L-lstdc++ \
    -L-lQtCore \
    -L-lsmokeqtcore \
    -L-lsmokeqtgui \
    -debug -d -inline \
    /tmp/qstring_cpp.o \
    examples/hello_world.d

if [ -f /tmp/qstring_cpp.o ]; then
    rm /tmp/qstring_cpp.o
fi

